"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Brain, User, AlertCircle, RefreshCw } from "lucide-react";
import { useAchievements } from "./AchievementContext";
import SpotlightCard from "./SpotlightCard";

interface Question {
  quote: string;
  source: "AI" | "Human";
  explanation: string;
}

const QUESTIONS: Question[] = [
  {
    quote: "The cloud is just someone else's computer.",
    source: "Human",
    explanation: "This is a famous computing adage coined by René Gielen in 2006 to describe cloud servers.",
  },
  {
    quote: "A modular array of microservices optimized to process neural graph telemetry and cross-node network packets through a serverless database connection.",
    source: "AI",
    explanation: "This statement is generated by an LLM, utilizing typical high-density tech buzzwords and complex sentence structures.",
  },
  {
    quote: "I enjoy turning ideas into reliable systems through automation, cloud technologies, artificial intelligence, and hands-on engineering.",
    source: "Human",
    explanation: "This is Allan's personal bio statement from the hero section of this website!",
  },
  {
    quote: "In computer science, a bug is not just an error in the logic; it is a footprint of the coder's subconscious mind grappling with abstract state spaces.",
    source: "AI",
    explanation: "This philosophical and poetic definition of a software bug was generated by an AI model when asked to write about debugging.",
  },
  {
    quote: "It worked yesterday. I have witnesses.",
    source: "Human",
    explanation: "A classic software engineering joke told by frustrated human developers for decades.",
  },
];

export default function Quiz() {
  const [currentIdx, setCurrentIdx] = useState(0);
  const [score, setScore] = useState(0);
  const [showResult, setShowResult] = useState(false);
  const [selectedAnswer, setSelectedAnswer] = useState<"AI" | "Human" | null>(null);
  const [hasAnswered, setHasAnswered] = useState(false);

  const { triggerQuizCompleted } = useAchievements();

  const handleAnswer = (choice: "AI" | "Human") => {
    if (hasAnswered) return;
    setSelectedAnswer(choice);
    setHasAnswered(true);

    if (choice === QUESTIONS[currentIdx].source) {
      setScore((prev) => prev + 1);
    }
  };

  const handleNext = () => {
    setSelectedAnswer(null);
    setHasAnswered(false);

    if (currentIdx < QUESTIONS.length - 1) {
      setCurrentIdx((prev) => prev + 1);
    } else {
      setShowResult(true);
      triggerQuizCompleted();
    }
  };

  const handleReset = () => {
    setCurrentIdx(0);
    setScore(0);
    setShowResult(false);
    setSelectedAnswer(null);
    setHasAnswered(false);
  };

  const currentQuestion = QUESTIONS[currentIdx];

  return (
    <SpotlightCard className="w-full rounded-xl p-5 border-glass-border flex flex-col h-full min-h-[350px] justify-between overflow-hidden relative select-none">
      {/* Title */}
      <div className="z-10 flex items-center justify-between border-b border-glass-border/40 pb-2">
        <h3 className="text-base font-semibold text-text flex items-center gap-2">
          <Brain className="w-5 h-5 text-accent" /> AI vs Human Quiz
        </h3>
        {!showResult && (
          <span className="text-xs text-muted">
            Question {currentIdx + 1} / {QUESTIONS.length}
          </span>
        )}
      </div>

      <AnimatePresence mode="wait">
        {!showResult ? (
          <motion.div
            key={currentIdx}
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
            className="flex-1 flex flex-col justify-center my-3"
          >
            {/* The Quote Block */}
            <div className="bg-[#0D1017]/60 border border-glass-border p-3.5 rounded-lg text-sm text-text leading-relaxed italic text-center min-h-[90px] flex items-center justify-center relative">
              <span className="absolute -top-2.5 -left-1 text-2xl text-accent/30 font-serif">“</span>
              <span>{currentQuestion.quote}</span>
              <span className="absolute -bottom-4 -right-1 text-2xl text-accent/30 font-serif">”</span>
            </div>

            {/* Action Buttons & Feedback */}
            {!hasAnswered ? (
              <div className="grid grid-cols-2 gap-3 mt-4">
                <button
                  onClick={() => handleAnswer("AI")}
                  className="bg-[#0D1017] border border-glass-border hover:border-accent/40 text-text py-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all active:scale-95 cursor-pointer"
                >
                  <Brain className="w-4 h-4 text-accent" /> AI Generated
                </button>
                <button
                  onClick={() => handleAnswer("Human")}
                  className="bg-[#0D1017] border border-glass-border hover:border-accent/40 text-text py-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all active:scale-95 cursor-pointer"
                >
                  <User className="w-4 h-4 text-accent" /> Human Authored
                </button>
              </div>
            ) : (
              <div className="mt-3 flex flex-col gap-2">
                <div className="flex items-center gap-2 text-xs">
                  {selectedAnswer === currentQuestion.source ? (
                    <span className="text-green-400 font-bold">✓ Correct!</span>
                  ) : (
                    <span className="text-red-400 font-bold">✗ Incorrect</span>
                  )}
                  <span className="text-muted-foreground">• Source: {currentQuestion.source}</span>
                </div>
                <p className="text-[11px] text-muted leading-relaxed bg-white/5 border border-glass-border/30 p-2 rounded">
                  {currentQuestion.explanation}
                </p>
                <button
                  onClick={handleNext}
                  className="bg-accent/15 border border-accent/30 hover:bg-accent/25 text-accent py-1.5 rounded-lg text-xs font-semibold self-end transition-all px-4 mt-1 active:scale-95"
                >
                  {currentIdx === QUESTIONS.length - 1 ? "Finish" : "Next Question"}
                </button>
              </div>
            )}
          </motion.div>
        ) : (
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="flex-1 flex flex-col items-center justify-center text-center gap-3 my-4"
          >
            <div className="text-4xl">
              {score === QUESTIONS.length ? "👑" : score >= 3 ? "🤖" : "👀"}
            </div>
            <div>
              <h4 className="text-sm font-bold text-text">Quiz Completed!</h4>
              <p className="text-xs text-muted mt-1">
                You got <span className="text-accent font-extrabold">{score} / {QUESTIONS.length}</span> correct guesses.
              </p>
              <p className="text-[11px] text-muted mt-2 max-w-[280px]">
                {score === QUESTIONS.length
                  ? "Flawless! You possess sharp engineering intuition."
                  : score >= 3
                  ? "Nice job! You can separate AI syntax from human humor pretty well."
                  : "AI is getting clever! Better keep studying those LLM outputs."}
              </p>
            </div>
            <button
              onClick={handleReset}
              className="bg-white/5 border border-glass-border hover:bg-white/10 text-text py-1.5 px-4 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-all mt-2 active:scale-95"
            >
              <RefreshCw className="w-3.5 h-3.5" /> Restart Quiz
            </button>
          </motion.div>
        )}
      </AnimatePresence>
    </SpotlightCard>
  );
}
