"use client";

import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Brain, User, AlertCircle, RefreshCw } from "lucide-react";
import { useAchievements } from "./AchievementContext";
import SpotlightCard from "./SpotlightCard";

interface Question {
  quote: string;
  source: "AI" | "Human";
  explanation: string;
}

const QUESTIONS: Question[] = [
  {
    quote: "The cloud is just someone else's computer.",
    source: "Human",
    explanation: "A classic industry joke coined by René Gielen in 2006 to remind developers of server realities.",
  },
  {
    quote: "A modular array of microservices optimized to process neural graph telemetry and cross-node network packets through a serverless database connection.",
    source: "AI",
    explanation: "Classic high-density buzzword soup generated by an LLM with no real architectural meaning.",
  },
  {
    quote: "I enjoy turning ideas into reliable systems through automation, cloud technologies, artificial intelligence, and hands-on engineering.",
    source: "Human",
    explanation: "This is Allan's personal bio statement from the hero section of this website!",
  },
  {
    quote: "In computer science, a bug is not just an error in the logic; it is a footprint of the coder's subconscious mind grappling with abstract state spaces.",
    source: "AI",
    explanation: "Generated by an AI asked to write a deep, poetic, and philosophical description of a bug.",
  },
  {
    quote: "It worked yesterday. I have witnesses.",
    source: "Human",
    explanation: "A classic software engineering joke told by frustrated human developers for decades.",
  },
  {
    quote: "An elegant algorithm is like a silent river, flowing through the silicon valleys of the processor, leaving no trace of computational overhead.",
    source: "AI",
    explanation: "Metaphorical, flowery, and slightly over-dramatic language typical of AI describing coding.",
  },
  {
    quote: "There are 10 types of people in the world: those who understand binary, and those who don't.",
    source: "Human",
    explanation: "One of the oldest binary puns in human history, originating in early programming forums.",
  },
  {
    quote: "The API endpoint utilizes asynchronous concurrency matrices to dynamically ingest multi-tenant telemetry datasets into a distributed cache framework.",
    source: "AI",
    explanation: "AI generated. It strings together high-level terms (concurrency matrices, telemetry datasets) that sound smart but are overly verbose.",
  },
  {
    quote: "Debugging is like being the detective in a crime movie where you are also the murderer.",
    source: "Human",
    explanation: "A famous quote by developer Filipe Fortes describing the self-inflicted nature of programming bugs.",
  },
  {
    quote: "To write clean code is to paint on a digital canvas where functions are strokes of logic and variables are colors of state.",
    source: "AI",
    explanation: "A highly artistic, slightly corny metaphor generated by AI to describe programming aesthetics.",
  },
  {
    quote: "There are only two hard things in Computer Science: cache invalidation and naming things.",
    source: "Human",
    explanation: "A legendary quote attributed to Phil Karlton, highlighting the real-world frustration of naming conventions.",
  },
  {
    quote: "A serverless function is a transient node in a decentralized cloud infrastructure, executing state transitions upon webhook triggers.",
    source: "AI",
    explanation: "Highly structured, technical, and textbook-like explanation generated by an AI model.",
  },
  {
    quote: "Real programmers count from 0.",
    source: "Human",
    explanation: "A simple joke about array indexing in programming languages like C, Java, and Python."
  },
  {
    quote: "The interface abstract class defines a contract of capability, decoupling the implementation architecture from the execution thread.",
    source: "AI",
    explanation: "AI-style technical summary: accurate but overly dry and academic."
  },
  {
    quote: "If at first you don't succeed, call it version 1.0.",
    source: "Human",
    explanation: "A cynical human developer joke about shipping minimum viable products to meet deadlines."
  },
  {
    quote: "Code is like poetry; it must be concise, expressive, and carry an implicit rhythm that guides the compiler through execution.",
    source: "AI",
    explanation: "AI text models love comparing code to poetry and writing about 'implicit rhythm'."
  },
  {
    quote: "A SQL query walks into a bar, walks up to two tables and asks, 'Can I join you?'",
    source: "Human",
    explanation: "A classic database developer dad joke."
  },
  {
    quote: "We leverage an automated CI/CD pipeline to seamlessly push dockerized container artifacts to our Kubernetes cluster.",
    source: "AI",
    explanation: "AI-generated corporate pitch using standard DevOps vocabulary in a very standard way."
  },
  {
    quote: "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.",
    source: "Human",
    explanation: "A famous quote by Bill Gates emphasizing that more code does not equal better software."
  },
  {
    quote: "The database query latency was optimized by introducing an index layer on high-cardinality columns, mitigating full table scans.",
    source: "AI",
    explanation: "A textbook diagnostic sentence commonly generated by AI assistants."
  },
  {
    quote: "Deleted code is debugged code.",
    source: "Human",
    explanation: "A minimalist rule of thumb from human developers who know that less code means fewer places for bugs to hide."
  },
  {
    quote: "A well-structured class hierarchy acts as a blueprint of digital inheritance, allowing subclasses to inherit core methods.",
    source: "AI",
    explanation: "A generic textbook definition of OOP inheritance, typical of AI generation."
  },
  {
    quote: "Walk softly and carry a big private key.",
    source: "Human",
    explanation: "A security developer play on Theodore Roosevelt's famous foreign policy quote."
  },
  {
    quote: "The model's hyperparameters were adjusted using grid search cross-validation to minimize cross-entropy loss over fifty epochs.",
    source: "AI",
    explanation: "A typical description of machine learning training generated by AI."
  },
  {
    quote: "There are two ways to write error-free programs; only the third one works.",
    source: "Human",
    explanation: "An ironical quote by Alan J. Perlis about the impossibility of writing perfect software."
  },
  {
    quote: "Through recursive traversal algorithms, we parse complex abstract syntax trees to identify code smell telemetry.",
    source: "AI",
    explanation: "Classic AI phrasing combining compiler theory with modern buzzwords like 'telemetry'."
  },
  {
    quote: "Most of you are familiar with the virtues of a programmer. There are three, of course: laziness, impatience, and hubris.",
    source: "Human",
    explanation: "A famous quote by Larry Wall, the creator of Perl, defining the mindset of productive developers."
  },
  {
    quote: "By containerizing our microservices, we ensure environment parity across local development, staging, and production environments.",
    source: "AI",
    explanation: "A standard corporate cloud explanation commonly generated by LLMs."
  },
  {
    quote: "The best thing about a boolean is even if you are wrong, you are only off by a bit.",
    source: "Human",
    explanation: "A clever binary pun about boolean logic."
  },
  {
    quote: "The garbage collector runs asynchronously in the virtual machine, reclaiming memory allocations that no longer possess references.",
    source: "AI",
    explanation: "A standard, formal description of memory management generated by an AI model."
  },
  {
    quote: "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.",
    source: "Human",
    explanation: "A famous programming proverb by John Woods, emphasizing the importance of clean, readable code."
  },
  {
    quote: "Our deep neural network architecture utilizes residual connections to mitigate the vanishing gradient problem during backpropagation.",
    source: "AI",
    explanation: "Standard AI-generated deep learning explanation."
  },
  {
    quote: "Weeks of coding can save you hours of planning.",
    source: "Human",
    explanation: "A sarcastic proverb highlighting the developer tendency to jump straight into coding instead of designing first."
  },
  {
    quote: "An asynchronous promise represents a proxy for a value not necessarily known when the promise is created.",
    source: "AI",
    explanation: "Very formal, MDN-like documentation wording typically output by AI assistants."
  },
  {
    quote: "Programming is 10% writing code and 90% understanding why it doesn't work.",
    source: "Human",
    explanation: "A relatable breakdown of the actual software development process."
  },
  {
    quote: "We configure a load balancer to distribute incoming HTTP traffic evenly across our auto-scaling EC2 instances.",
    source: "AI",
    explanation: "A standard cloud deployment sentence generated by AI."
  },
  {
    quote: "Documentation is like insurance: everyone agrees it's important, but nobody wants to pay for it.",
    source: "Human",
    explanation: "A classic developer joke about the lack of documentation in most codebases."
  },
  {
    quote: "The compiler translates source code into machine-readable bytecode, which is then executed by the virtual machine.",
    source: "AI",
    explanation: "A plain, textbook description of compilation generated by an AI."
  },
  {
    quote: "A good programmer is someone who always looks both ways before crossing a one-way street.",
    source: "Human",
    explanation: "A humorous quote by Doug Linder about the defensive mindset required for programming."
  },
  {
    quote: "To optimize response times, we implemented a redis cache layer to store frequently accessed database records.",
    source: "AI",
    explanation: "Generic architectural description typical of AI system designs."
  },
  {
    quote: "Computers are good at following instructions, but not at reading your mind.",
    source: "Human",
    explanation: "A common developer saying explaining why bugs exist—the computer did exactly what you wrote, not what you wanted."
  },
  {
    quote: "The security protocol implements end-to-end encryption using AES-256 to safeguard user telemetry in transit.",
    source: "AI",
    explanation: "Standard security boilerplate text generated by AI."
  },
  {
    quote: "Make it work, make it right, make it fast.",
    source: "Human",
    explanation: "A famous software development guideline popularized by Kent Beck, pioneer of Extreme Programming."
  },
  {
    quote: "Using a git merge conflict resolution tool allows developers to compare diff branches side by side.",
    source: "AI",
    explanation: "AI generated: accurate but extremely plain and descriptive."
  },
  {
    quote: "Complexity is easy; simplicity is hard.",
    source: "Human",
    explanation: "A fundamental design philosophy articulated by many software pioneers like Edsger W. Dijkstra."
  },
  {
    quote: "We structure our codebase using clean architecture principles, separating the domain entities from database adapters.",
    source: "AI",
    explanation: "Standard software architecture boilerplate description commonly generated by AI."
  },
  {
    quote: "Java is to JavaScript what car is to Carpet.",
    source: "Human",
    explanation: "A famous developer analogy coined by Greg Brown to highlight that the two languages are entirely unrelated despite their names."
  },
  {
    quote: "The web scraper handles pagination and rate limiting dynamically to avoid triggering IP blocks.",
    source: "AI",
    explanation: "Standard AI-style coding task description."
  },
  {
    quote: "If Java had true garbage collection, most programs would delete themselves upon execution.",
    source: "Human",
    explanation: "A savage classic developer burn directed at Java's memory footprint and design."
  },
  {
    quote: "By adopting a serverless model, developers can focus on writing business logic without worrying about server provisioning.",
    source: "AI",
    explanation: "A promotional cloud computing sentence commonly output by AI models."
  },
  {
    quote: "Real programmers use COPY CON.",
    source: "Human",
    explanation: "An old-school developer joke referencing DOS file creation commands, indicating extreme minimalism."
  },
  {
    quote: "A binary search tree provides log-time search, insert, and delete operations, maintaining sorted key telemetry.",
    source: "AI",
    explanation: "Classic AI phrasing combining standard computer science facts with unnecessary buzzwords like 'telemetry'."
  }
];

export default function Quiz() {
  const [mounted, setMounted] = useState(false);
  const [activeQuestions, setActiveQuestions] = useState<Question[]>([]);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [score, setScore] = useState(0);
  const [showResult, setShowResult] = useState(false);
  const [selectedAnswer, setSelectedAnswer] = useState<"AI" | "Human" | null>(null);
  const [hasAnswered, setHasAnswered] = useState(false);

  const { triggerQuizCompleted } = useAchievements();

  const generateRandomQuestions = () => {
    const shuffled = [...QUESTIONS].sort(() => 0.5 - Math.random());
    setActiveQuestions(shuffled.slice(0, 5));
    setCurrentIdx(0);
    setScore(0);
    setShowResult(false);
    setSelectedAnswer(null);
    setHasAnswered(false);
  };

  useEffect(() => {
    setMounted(true);
    generateRandomQuestions();
  }, []);

  const handleAnswer = (choice: "AI" | "Human") => {
    if (hasAnswered || activeQuestions.length === 0) return;
    setSelectedAnswer(choice);
    setHasAnswered(true);

    if (choice === activeQuestions[currentIdx].source) {
      setScore((prev) => prev + 1);
    }
  };

  const handleNext = () => {
    setSelectedAnswer(null);
    setHasAnswered(false);

    if (currentIdx < activeQuestions.length - 1) {
      setCurrentIdx((prev) => prev + 1);
    } else {
      setShowResult(true);
      triggerQuizCompleted();
    }
  };

  const handleReset = () => {
    generateRandomQuestions();
  };

  if (!mounted || activeQuestions.length === 0) {
    return (
      <SpotlightCard className="w-full rounded-xl p-5 border-glass-border flex flex-col h-full min-h-[350px] justify-between overflow-hidden relative select-none">
        <div className="z-10 flex items-center justify-between border-b border-glass-border/40 pb-2">
          <h3 className="text-base font-semibold text-text flex items-center gap-2">
            <Brain className="w-5 h-5 text-accent" /> AI vs Human Quiz
          </h3>
        </div>
        <div className="flex-1 flex items-center justify-center">
          <span className="text-xs text-muted">Initialising sandbox...</span>
        </div>
      </SpotlightCard>
    );
  }

  const currentQuestion = activeQuestions[currentIdx];

  return (
    <SpotlightCard className="w-full rounded-xl p-5 border-glass-border flex flex-col h-full min-h-[350px] justify-between overflow-hidden relative select-none">
      {/* Title */}
      <div className="z-10 flex items-center justify-between border-b border-glass-border/40 pb-2">
        <h3 className="text-base font-semibold text-text flex items-center gap-2">
          <Brain className="w-5 h-5 text-accent" /> AI vs Human Quiz
        </h3>
      </div>

      <AnimatePresence mode="wait">
        {!showResult ? (
          <motion.div
            key={currentIdx}
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
            className="flex-1 flex flex-col justify-center my-3"
          >
            {/* The Quote Block */}
            <div className="bg-[#0D1017]/60 border border-glass-border p-3.5 rounded-lg text-sm text-text leading-relaxed italic text-center min-h-[90px] flex items-center justify-center relative">
              <span className="absolute -top-2.5 -left-1 text-2xl text-accent/30 font-serif">“</span>
              <span>{currentQuestion.quote}</span>
              <span className="absolute -bottom-4 -right-1 text-2xl text-accent/30 font-serif">”</span>
            </div>

            {/* Action Buttons & Feedback */}
            {!hasAnswered ? (
              <div className="grid grid-cols-2 gap-3 mt-4">
                <button
                  onClick={() => handleAnswer("AI")}
                  className="bg-[#0D1017] border border-glass-border hover:border-accent/40 text-text py-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all active:scale-95 cursor-pointer"
                >
                  <Brain className="w-4 h-4 text-accent" /> AI Generated
                </button>
                <button
                  onClick={() => handleAnswer("Human")}
                  className="bg-[#0D1017] border border-glass-border hover:border-accent/40 text-text py-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all active:scale-95 cursor-pointer"
                >
                  <User className="w-4 h-4 text-accent" /> Human Authored
                </button>
              </div>
            ) : (
              <div className="mt-3 flex flex-col gap-2">
                <div className="flex items-center gap-2 text-xs">
                  {selectedAnswer === currentQuestion.source ? (
                    <span className="text-green-400 font-bold">✓ Correct!</span>
                  ) : (
                    <span className="text-red-400 font-bold">✗ Incorrect</span>
                  )}
                  <span className="text-muted-foreground">• Source: {currentQuestion.source}</span>
                </div>
                <p className="text-[11px] text-muted leading-relaxed bg-white/5 border border-glass-border/30 p-2 rounded">
                  {currentQuestion.explanation}
                </p>
                <button
                  onClick={handleNext}
                  className="bg-accent/15 border border-accent/30 hover:bg-accent/25 text-accent py-1.5 rounded-lg text-xs font-semibold self-end transition-all px-4 mt-1 active:scale-95"
                >
                  {currentIdx === activeQuestions.length - 1 ? "Finish" : "Next Question"}
                </button>
              </div>
            )}
          </motion.div>
        ) : (
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="flex-1 flex flex-col items-center justify-center text-center gap-3 my-4"
          >
            <div className="text-4xl">
              {score === activeQuestions.length ? "👑" : score >= 3 ? "🤖" : "👀"}
            </div>
            <div>
              <h4 className="text-sm font-bold text-text">Quiz Completed!</h4>
              <p className="text-xs text-muted mt-1">
                You got <span className="text-accent font-extrabold">{score} / {activeQuestions.length}</span> correct guesses.
              </p>
              <p className="text-[11px] text-muted mt-2 max-w-[280px]">
                {score === activeQuestions.length
                  ? "Flawless! You possess sharp engineering intuition."
                  : score >= 3
                  ? "Nice job! You can separate AI syntax from human humor pretty well."
                  : "AI is getting clever! Better keep studying those LLM outputs."}
              </p>
            </div>
            <button
              onClick={handleReset}
              className="bg-white/5 border border-glass-border hover:bg-white/10 text-text py-1.5 px-4 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-all mt-2 active:scale-95"
            >
              <RefreshCw className="w-3.5 h-3.5" /> Restart Quiz
            </button>
          </motion.div>
        )}
      </AnimatePresence>
    </SpotlightCard>
  );
}
